### ISSUE TITLE
Reloading Failure

### ISSUE THREAD

**Issue by CitrusHappy** [StijnArts/Pixelmon-Create-Compat#1]
Looks like some item and block tags are missing references, this causes reloading with the /reload command to fail.

[link to part of latest.log that is relevant](https://gist.github.com/CitrusHappy/404c97e71e3d363211cac1015e51b73c)

lmk if more is needed

**Comment by CitrusHappy** [comment]
this same error occurs when restarting worlds, since the world loads up again, causing it to make the world unopenable

**Comment by StijnArts** [comment]
This'll be fixed next update, which should come out later today.
